version: '3.7'

services:
  redis:
    container_name: redis 
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
     - /path/to/local/d–∞ta:/root/redis
     - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  app-responsables:
    container_name: app-responsables 
    image: elparra/responsables:latest
    ports:
      - 8082:8082
    environment:
      SCOPE: local
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    depends_on:
      - redis
      
      
  app-activos:
    container_name: app-activos
    image: elparra/activos:latest
    ports:
      - 8081:8081
    environment:
      SCOPE: local
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    depends_on:
      - redis



    